tasks:
  - name: Solana
    command: sh -c "$(curl -sSfL https://release.solana.com/v1.10.7/install)" && export PATH="/home/gitpod/.local/share/solana/install/active_release/bin:$PATH" && solana --version

    
    
  - name: Yarn
    command: npm i -globall yarn && yarn --version
    
    
    
  - name: Ts-node
    command: npm i -g typescript && npm i -g ts-node
    
    
    
  - name: Dir
    command: solana-keygen new --outfile ./solana-nft/my-keypair.json
    
    
    
    
    
                                                                                                                                                                                                                    
