tasks:
  - name: Solana
    command: sh -c "$(curl -sSfL https://release.solana.com/v1.10.7/install)"

    
    
  - name: Yarn
    command: npm i -globall yarn 
    
    
    
  - name: Ts-node
    command: npm i -g typescript && npm i -g ts-node
    
    
    
  - name: Dir
    init: cd solana-nft && solana-keygen new --outfile ./my-keypair.json
    
    
    
    
    
                                                                                                                                                                                                                    